### PR TITLE
Set version from Makefile

### PR DESCRIPTION
**Pull request by dgellow**
- Set the version only in the Makefile instead of at two different places (Makefile and DEBIAN/control)
- Use a conditional assignment of `COMPOSER_VERSION` to allow variable overriding

### CODE REVIEW

**Comment by dgellow** [comment]
@RobLoach I don't know what is the file `s`. No sure if it need to be updated.

**Comment by RobLoach** [comment]
> I don't know what is the file s. No sure if it need to be updated.

Think we should just delete it?

**Comment by dgellow** [comment]
@RobLoach done

**Comment by dgellow** [comment]
bump?

**Comment by RobLoach** [comment]
Looks good! Thanks for the ping.

**Pull request merged**
